#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
OUT = ROOT / "src" / "EmbeddedUi.h"


def read_utf8(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def choose_delim(contents: str, base: str) -> str:
    delim = base
    i = 0
    while f'){delim}"' in contents:
        i += 1
        delim = f"{base}_{i}"
    return delim


def raw_literal(var_name: str, mime_comment: str, contents: str, base_delim: str) -> str:
    delim = choose_delim(contents, base_delim)
    return (
        f"// {mime_comment}\n"
        f"static const char {var_name}[] PROGMEM = R\"{delim}(\n"
        f"{contents}\n"
        f"){delim}\";\n"
    )


def main() -> None:
    index_html = read_utf8(DATA_DIR / "index.html").rstrip("\n")
    styles_css = read_utf8(DATA_DIR / "styles.css").rstrip("\n")
    app_js = read_utf8(DATA_DIR / "app.js").rstrip("\n")

    out = []
    out.append("#pragma once\n")
    out.append("\n")
    out.append("#include <pgmspace.h>\n")
    out.append("\n")
    out.append("// Embedded UI assets (served directly from flash).\n")
    out.append("// Generated by tools/gen_embedded_ui.py from /data.\n")
    out.append("\n")

    out.append(raw_literal("kEmbeddedIndexHtml", "text/html", index_html, "SMARTSHABAT_HTML"))
    out.append("\n")
    out.append(raw_literal("kEmbeddedStylesCss", "text/css", styles_css, "SMARTSHABAT_CSS"))
    out.append("\n")
    out.append(raw_literal("kEmbeddedAppJs", "application/javascript", app_js, "SMARTSHABAT_JS"))

    OUT.write_text("".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()

